name: fetch
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.11.10
  - pip
  - numpy=1.26.4
  - pandas=2.2.3
  - pytorch=2.1.2
  - jupyter=1.1.1
  - notebook=7.2.2
  - pip:
      - transformers==4.45.2